### ISSUE TITLE
not installing on Blender 2.8 on windows

### ISSUE THREAD

**Issue by j2l** [michaeldegroot/cats-blender-plugin#103]
I tried both as normal user and administrator and get:

### Loading CATS...
```
Checking for CATS files in the addon directory:
C:\Users\nobody\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons
Loading Updater..
REGISTER CATS UPDATER
Loading settings..
Loading mmd_tools..
mmd_tools_local registed 127 classes
Registering CATS classes..
Registered 109 CATS classes.
Registering scene types..
Loading other stuff..
Exception in module register(): C:\Users\nobody\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\cats-blender-plugin-0-12-2\__init__.py
Traceback (most recent call last):
  File "C:\Users\nobody\Documents\blender-2.80-96f762500ef9-win64\blender-2.80.0-git.96f762500ef9-windows64\2.80\scripts\modules\addon_utils.py", line 393, in enable
    mod.register()
  File "C:\Users\nobody\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\cats-blender-plugin-0-12-2\__init__.py", line 324, in register
    tools.common.get_user_preferences().system.use_international_fonts = True
AttributeError: 'PreferencesSystem' object has no attribute 'use_international_fonts'


### Loading CATS...
Checking for CATS files in the addon directory:
C:\Users\nobody\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons
Loading Updater..
REGISTER CATS UPDATER
Exception in module register(): C:\Users\nobody\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\cats-blender-plugin-0-12-2\__init__.py
Traceback (most recent call last):
  File "C:\Users\nobody\Documents\blender-2.80-96f762500ef9-win64\blender-2.80.0-git.96f762500ef9-windows64\2.80\scripts\modules\addon_utils.py", line 393, in enable
    mod.register()
  File "C:\Users\nobody\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\cats-blender-plugin-0-12-2\__init__.py", line 266, in register
    updater.register(bl_info, dev_branch, version_str)
  File "C:\Users\nobody\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\cats-blender-plugin-0-12-2\updater.py", line 928, in register
    bpy.utils.register_class(cls)
ValueError: register_class(...): already registered as a subclass
```

Any idea?

**Comment by j2l** [comment]
Needed dev branch and not release.
