### ISSUE TITLE
mmd_tools is not 2.80 compatible?

### ISSUE THREAD

**Issue by kkartaltepe** [michaeldegroot/cats-blender-plugin#127]
mmd_tools appears to use 2.79 attributes that have been removed in 2.80, specifically
https://github.com/michaeldegroot/cats-blender-plugin/blob/master/extern_tools/mmd_tools_local/core/material.py#L112

From the 2.80 docs that attribute seems to no longer exist https://docs.blender.org/api/blender2.8/bpy.types.Image.html

Results in a crash on import model:
```
Traceback (most recent call last):
  File "...\cats-blender-plugin-0-13-2\extern_tools\mmd_tools_local\properties\material.py", line 36, in _updateToonTexture
    FnMaterial(prop.id_data).update_toon_texture()
  File "...\cats-blender-plugin-0-13-2\extern_tools\mmd_tools_local\core\material.py", line 273, in update_toon_texture
    self.create_toon_texture(mmd_mat.toon_texture)
  File "...\cats-blender-plugin-0-13-2\extern_tools\mmd_tools_local\core\material.py", line 444, in create_toon_texture
    texture = self.__create_texture_node('mmd_toon_tex', filepath, (-3, -1.5))
  File "...\cats-blender-plugin-0-13-2\extern_tools\mmd_tools_local\core\material.py", line 475, in __create_texture_node
    texture.image = self._load_image(filepath)
  File "...\cats-blender-plugin-0-13-2\extern_tools\mmd_tools_local\core\material.py", line 112, in _load_image
    img.use_alpha = (img.depth == 32 and img.file_format != 'BMP')
AttributeError: 'Image' object has no attribute 'use_alpha'
```

**Comment by Darkblader24** [comment]
I know, but thanks for the report. I'm just waiting for mmd_tools to be updated, then I will release a new cats version.

**Comment by kkartaltepe** [comment]
Ah I see there is a relevant commit in the development branch. This should be called out in the readme which states 2.80 compatibility in the "Requirements" section imo.

**Comment by kkartaltepe** [comment]
Works fine in dev branch.

**Comment by Darkblader24** [comment]
The API of Blender 2.80 finally went stable a few days ago, so cats should no longer break after the next update
