### ISSUE TITLE
Add numpy to requirements

### ISSUE THREAD

**Issue by jug007** [michaeldegroot/cats-blender-plugin#145]
Apparently the plugin uses numpy, which is not nessesarily installed.
On my system I got this error message when trying to run the plugin out of the box:
```
Traceback (most recent call last):
  File "/usr/share/blender/scripts/modules/addon_utils.py", line 331, in enable
    mod = import(module_name)
  File "/home/motofckr9k/.config/blender/2.79/scripts/addons/cats-blender-plugin-master/init.py", line 71, in <module>
    import mmd_tools_local
  File "/home/motofckr9k/.config/blender/2.79/scripts/addons/cats-blender-plugin-master/extern_tools/mmd_tools_local/init.py", line 51, in <module>
    from . import properties
  File "/home/motofckr9k/.config/blender/2.79/scripts/addons/cats-blender-plugin-master/extern_tools/mmd_tools_local/properties/init.py", line 16, in <module>
    from . import (
  File "/home/motofckr9k/.config/blender/2.79/scripts/addons/cats-blender-plugin-master/extern_tools/mmd_tools_local/properties/root.py", line 12, in <module>
    from mmd_tools_local.core.sdef import FnSDEF
  File "/home/motofckr9k/.config/blender/2.79/scripts/addons/cats-blender-plugin-master/extern_tools/mmd_tools_local/core/sdef.py", line 4, in <module>
    import numpy as np
ModuleNotFoundError: No module named 'numpy'
```
Apparently numpy for python2 was installed on my system already, but numpy for python3 (which blender is using) wasn't.
For reference I am using Linux Mint 19.1, which is based on Ubuntu 18.04.
the package I needed to install was called "python3-numpy"

**Comment by Darkblader24** [comment]
Done!
