### ISSUE TITLE
Unable to enable Cats in Blender 2.81 (OSError: [WinError 193] %1 is not a valid Win32 application)

### ISSUE THREAD

**Issue by IonDworth** [michaeldegroot/cats-blender-plugin#170]
Every time I try to enable Cats in Blender 2.81, it throws this error:
Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 2.81\2.81\scripts\modules\addon_utils.py", line 351, in enable
    mod = __import__(module_name)
  File "C:\Users\chris\AppData\Roaming\Blender Foundation\Blender\2.81\scripts\addons\cats-blender-plugin-0-16-1\__init__.py", line 65, in <module>
    import mmd_tools_local
  File "C:\Users\chris\AppData\Roaming\Blender Foundation\Blender\2.81\scripts\addons\cats-blender-plugin-0-16-1\extern_tools\mmd_tools_local\__init__.py", line 51, in <module>
    from . import properties
  File "C:\Users\chris\AppData\Roaming\Blender Foundation\Blender\2.81\scripts\addons\cats-blender-plugin-0-16-1\extern_tools\mmd_tools_local\properties\__init__.py", line 16, in <module>
    from . import (
  File "C:\Users\chris\AppData\Roaming\Blender Foundation\Blender\2.81\scripts\addons\cats-blender-plugin-0-16-1\extern_tools\mmd_tools_local\properties\root.py", line 12, in <module>
    from mmd_tools_local.core.sdef import FnSDEF
  File "C:\Users\chris\AppData\Roaming\Blender Foundation\Blender\2.81\scripts\addons\cats-blender-plugin-0-16-1\extern_tools\mmd_tools_local\core\sdef.py", line 4, in <module>
    import numpy as np
  File "C:\Users\chris\AppData\Roaming\Python\Python37\site-packages\numpy\__init__.py", line 142, in <module>
    from . import core
  File "C:\Users\chris\AppData\Roaming\Python\Python37\site-packages\numpy\core\__init__.py", line 23, in <module>
    WinDLL(os.path.abspath(filename))
  File "C:\Program Files\Blender Foundation\Blender 2.81\2.81\python\lib\ctypes\__init__.py", line 364, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 193] %1 is not a valid Win32 application

**Comment by Darkblader24** [comment]
Do you have a custom Python installed that could overwrite the Python path of Blender? If yes, either remove it or install Numpy into it.

**Comment by IonDworth** [comment]
I got it to work. I had to delete numpy from C:\Users\%userfolder%\AppData\Roaming\Python\Python37\site-packages. It works perfectly now.
