### ISSUE TITLE
I get an error whenever i try to fix a model in cats

### ISSUE THREAD

**Issue by L0L1Master** [michaeldegroot/cats-blender-plugin#182]
I get this error

Traceback (most recent call last):
  File "C:\Users\joshu\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\cats-blender-plugin-master\tools\armature.py", line 344, in execute
    bpy.ops.cats_material.combine_mats()
  File "D:\Blender\2.82\scripts\modules\bpy\ops.py", line 201, in __call__
    ret = op_call(self.idname_py(), None, kw)
RuntimeError: Operator bpy.ops.cats_material.combine_mats.poll() failed, context is incorrect

location: <unknown location>:-1

**Comment by L0L1Master** [comment]
I figured it out I forgot to name my mesh Body
