### ISSUE TITLE
CATS does not enable on in Blender 2.83 beta.

### ISSUE THREAD

**Issue by glencoe2004** [michaeldegroot/cats-blender-plugin#183]
Attempting to activate the plugin gives this error:

---
### Loading CATS...
Skipped 11 CATS updater classes.
mmd_tools is already registered
Skipped 106 CATS classes.
Exception ignored in: <function ImagePreviewCollection.__del__ at 0x000002394EB8C1F8>
Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 2.83 Beta\2.83\scripts\modules\bpy\utils\previews.py", line 79, in __del__
    f"{self!r}: left open, remove with "
ResourceWarning: <ImagePreviewCollection id=0x23956dca468[5], <super: <class 'ImagePreviewCollection'>, <ImagePreviewCollection object>>>: left open, remove with 'bpy.utils.previews.remove()'
Exception in module register(): C:\Users\(name)\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\cats-blender-plugin-0-16-1\__init__.py
Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 2.83 Beta\2.83\scripts\modules\addon_utils.py", line 382, in enable
    mod.register()
  File "C:\Users\(name)\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\cats-blender-plugin-0-16-1\__init__.py", line 322, in register
    tools.common.get_user_preferences().view.use_international_fonts = True
AttributeError: 'PreferencesView' object has no attribute 'use_international_fonts'
---

Thank you.

**Comment by leucome** [comment]
There is a similar issue with Blender 2.90.

**Comment by Darkblader24** [comment]
Hey, thanks for the report, this is fixed in the dev version of cats
