### ISSUE TITLE
"Fix Model" fails on models that have no UVmap

### ISSUE THREAD

**Issue by antether** [michaeldegroot/cats-blender-plugin#66]
Can always be reproduced by removed all uvmaps from a model and clicking "Fix Model".  The error message is as follow.
```

Traceback (most recent call last):
  File "C:\Users\User\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\cats-blender-plugin-master\tools\armature.py", line 237, in execute
    mesh = tools.common.join_meshes()
  File "C:\Users\User\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\cats-blender-plugin-master\tools\common.py", line 571, in join_meshes
    mesh.data.uv_textures[0].name = 'UVMap'
IndexError: bpy_prop_collection[index]: index 0 out of range, size 0

location: <unknown location>:-1


```

**Comment by Darkblader24** [comment]
Thanks, fixed!
