### ISSUE TITLE
OScannot identify image file for all `dds` images

### ISSUE THREAD

**Issue by arijoon** [michaeldegroot/cats-blender-plugin#70]
This seems to be happening for all `dds` files. It seems to be from the underlying `Image` class.

```
location: C:\Program Files\Blender Foundation\Blender\2.79\scripts\modules\bpy\ops.py:187
Error: Traceback (most recent call last):
  File "C:\Users\ayara\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\material-combiner-addon-master\one_mat.py", line 181, in execute
    else (x.name, x) for x in files)],
  File "C:\Users\ayara\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\material-combiner-addon-master\one_mat.py", line 179, in <listcomp>
    images = sorted([{'w': i.size[0], 'h': i.size[1], 'path': path, 'img': i}
  File "C:\Users\ayara\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\material-combiner-addon-master\one_mat.py", line 181, in <genexpr>
    else (x.name, x) for x in files)],
  File "C:\Users\ayara\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\material-combiner-addon-master\PIL\Image.py", line 2622, in open
    % (filename if filename else fp))

Error: Traceback (most recent call last):
  File "C:\Users\ayara\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\material-combiner-addon-master\one_mat.py", line 181, in execute
    else (x.name, x) for x in files)],
  File "C:\Users\ayara\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\material-combiner-addon-master\one_mat.py", line 179, in <listcomp>
    images = sorted([{'w': i.size[0], 'h': i.size[1], 'path': path, 'img': i}
  File "C:\Users\ayara\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\material-combiner-addon-master\one_mat.py", line 181, in <genexpr>
    else (x.name, x) for x in files)],
  File "C:\Users\ayara\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\material-combiner-addon-master\PIL\Image.py", line 2622, in open
    % (filename if filename else fp))
```

OS: Windows

This happens during Atlas creation.

Additional stack before that exception:

```
Importing BlpImagePlugin
Image: failed to import BlpImagePlugin: No module named 'PIL'
Importing BmpImagePlugin
Image: failed to import BmpImagePlugin: No module named 'PIL'
... same for all modules in _plugins array
```

So the problem is with importing. It does not recognize `PIL` as a module. I manually edited all the files and made them use `from . import module_name` syntax. I would love to see a real solution to this

This seems to suggest there is something seriously wrong while it is trying to import pillow module

**Comment by Darkblader24** [comment]
Those errors are not the full errors. Full errors are way more helpful. But from your title I suppose that dds files are simply not supported. 
And regarding the PIL import error, you might want to check out the forum thread of the material combiner. I remember being talked about that in the comments, you might need a different version.

**Comment by arijoon** [comment]
My apologies I should have closed this last night, I debugged it and found the issue, it's imports that are not working as expected in the py env belnder runs the addons. I manually hacked it to get it to work, this is a problem with materials combiner or my environment and has nothing to do with CATS.
