### ISSUE TITLE
Fix Model Error on Blender 2.79b Mac

### ISSUE THREAD

**Issue by UiharuKazari2008** [michaeldegroot/cats-blender-plugin#75]
Traceback (most recent call last):
  File "/Users/kazari/Library/Application Support/Blender/2.79/scripts/addons/cats-blender-plugin-master/tools/armature.py", line 327, in execute
    if math.isnan(uv.data[vert].uv.y):
  File "/Users/kazari/Library/Application Support/Blender/2.79/scripts/addons/cats-blender-plugin-master/tools/translate.py", line 409, in update_dictionary
    google_input.append(name)
  File "/Users/kazari/Library/Application Support/Blender/2.79/scripts/addons/cats-blender-plugin-master/googletrans/client.py", line 134, in translate
    result = []
  File "/Users/kazari/Library/Application Support/Blender/2.79/scripts/addons/cats-blender-plugin-master/googletrans/client.py", line 142, in translate
    
  File "/Users/kazari/Library/Application Support/Blender/2.79/scripts/addons/cats-blender-plugin-master/googletrans/client.py", line 60, in _translate
    token = self.token_acquirer.do(text)
  File "/Users/kazari/Library/Application Support/Blender/2.79/scripts/addons/cats-blender-plugin-master/googletrans/gtoken.py", line 188, in do
    
  File "/Users/kazari/Library/Application Support/Blender/2.79/scripts/addons/cats-blender-plugin-master/googletrans/gtoken.py", line 67, in _update
    self.tkk = newtkk.group(1)
AttributeError: 'NoneType' object has no attribute 'group'

location: <unknown location>:-1

Same as Issues 63 but I am running the latest version. This only happenes with some models

**Comment by Darkblader24** [comment]
Oh, this really happens? Looking at the code this should be impossible. But I will implement something in the dev version of cats which I can use to find the cause of this error. Please join the cats discord so I can get back to you faster: https://discord.gg/f8yZGnv

**Comment by Darkblader24** [comment]
I just added a button to the development version of cats: https://i.imgur.com/Ioc5dyN.png
Please update to the development version with the build-in updater, press this button and send me the file in your cats addon folder > resources > "google-response.txt"

**Comment by Darkblader24** [comment]
Fixed. If you have the same error again, please let me know
